name: a11y-slides-math release
# PURPOSE:
#
#  1. create release and upload a11y-slides-math-template.html
#
# Note: this action only runs on *each release*, i.e. when tags are pushed
#

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: 'a11y-slides-math create release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      # 
      # body of release is read from documentation/changelog.md
      #
      - name: get changelog.md information
        run: |
          csplit docs/changelog.md '/^\#\#/' '{*}' -f cmh # split changelog at '##'
          sed -i.bak s/\#\#.*\// cmh01                             # 
          mv cmh01 a11y-slides-math-release.md
          cat a11y-slides-math-release.md
      - name: a11y-slides-math release
        uses: softprops/action-gh-release@v2
        with:
          body_path: a11y-slides-math-release.md
          files: |
            a11y-slides-math-template.html
